id: IA1585AAF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T15:18:55+00:00'
last_modified: '2022-06-15T15:26:15.441597+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6248
  title: རེབ་ཀོང་རུས་མཛོད་ལྟ་བ་མཁའ་ཁྱབ་ཕྱོགས་བྲལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    63D6:
      image_group_id: I1KG10627
      title: Volume 1 of reb kong rus mdzod lta ba mkha' khyab phyogs bral/
      total_pages: 766
      order: 1
      base_file: 63D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
